export const CREATE_REVIEW_REQUEST = "CREATE_REVIEW_REQUEST"
export const CREATE_REVIEW_SUCCESS = "CREATE_REVIEW_SUCCESS"
export const CREATE_REVIEW_ERROR = "CREATE_REVIEW_ERROR"

export const GET_REVIEW_REQUEST = "GET_REVIEW_REQUEST"
export const GET_REVIEW_SUCCESS = "GET_REVIEW_SUCCESS"
export const GET_REVIEW_ERROR = "GET_REVIEW_ERROR"

export const CREATE_RATING_REQUEST = "CREATE_RATING_REQUEST"
export const CREATE_RATING_SUCCESS = "CREATE_RATING_SUCCESS"
export const CREATE_RATING_ERROR = "CREATE_RATING_ERROR"


export const GET_RATING_REQUEST = "GET_RATING_REQUEST"
export const GET_RATING_SUCCESS = "GET_RATING_SUCCESS"
export const GET_RATING_ERROR = "GET_RATING_ERROR"
