export const ADD_ITEM_CART_REQ = "ADD_ITEM_CART_REQ"
export const ADD_ITEM_CART_SUCCESS = "ADD_ITEM_CART_SUCCESS"
export const ADD_ITEM_CART_ERROR = "ADD_ITEM_CART_ERROR"

export const GET_CART_REQUEST = "GET_CART_REQUEST"
export const GET_CART_SUCCESS = "GET_CART_SUCCESS"
export const GET_CART_ERROR = "GET_CART_ERROR"

export const REMOVE_ITEM_CART_REQUEST = "REMOVE_ITEM_CART_REQUEST"
export const REMOVE_ITEM_CART_SUCCESS = "REMOVE_ITEM_CART_SUCCESS"
export const REMOVE_ITEM_CART_ERROR = "REMOVE_ITEM_CART_ERROR"

export const UPDATE_ITEM_CART_REQUEST = "UPDATE_ITEM_CART_REQUEST"
export const UPDATE_ITEM_CART_SUCCESS = "UPDATE_ITEM_CART_SUCCESS"
export const UPDATE_ITEM_CART_ERROR = "UPDATE_ITEM_CART_ERROR"