export const FIND_PRODUCT_REQUEST = "FIND_PRODUCT_REQUEST"
export const FIND_PRODUCT_SUCCESS = "FIND_PRODUCT_SUCCESS"
export const FIND_PRODUCT_ERROR = "FIND_PRODUCT_ERROR"

export const FIND_PRODUCTS_REQUEST = "FIND_PRODUCTS_REQUEST"
export const FIND_PRODUCTS_SUCCESS = "FIND_PRODUCTS_SUCCESS"
export const FIND_PRODUCTS_ERROR = "FIND_PRODUCTS_ERROR"

