export const LEVEL_ONE_CATEGORY_REQUEST = "LEVEL_ONE_CATEGORY_REQUEST"
export const LEVEL_ONE_CATEGORY_SUCCESS = "LEVEL_ONE_CATEGORY_SUCCESS"
export const LEVEL_ONE_CATEGORY_ERROR = "LEVEL_ONE_CATEGORY_ERROR"


export const LEVEL_TWO_CATEGORY_REQUEST = "LEVEL_TWO_CATEGORY_REQUEST"
export const LEVEL_TWO_CATEGORY_SUCCESS = "LEVEL_TWO_CATEGORY_SUCCESS"
export const LEVEL_TWO_CATEGORY_ERROR = "LEVEL_TWO_CATEGORY_ERROR"



export const LEVEL_THREE_CATEGORY_REQUEST = "LEVEL_THREE_CATEGORY_REQUEST"
export const LEVEL_THREE_CATEGORY_SUCCESS = "LEVEL_THREE_CATEGORY_SUCCESS"
export const LEVEL_THREE_CATEGORY_ERROR = "LEVEL_THREE_CATEGORY_ERROR"
