

export const CREATE_RATING_REQUEST = "CREATE_RATING_REQUEST"
export const CREATE_RATING_SUCCESS = "CREATE_RATING_SUCCESS"
export const CREATE_RATING_ERROR = "CREATE_RATING_ERROR"


export const GET_RATING_REQUEST = "GET_RATING_REQUEST"
export const GET_RATING_SUCCESS = "GET_RATING_SUCCESS"
export const GET_RATING_ERROR = "GET_RATING_ERROR"
